name: scc
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.15.1=py37h5eee18b_3
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - hdf5=1.10.6=h3ffc7dd_1
  - idna=3.4=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h7b6447c_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - pytables=3.7.0=py37hf19a122_1
  - python=3.7.16=h7a1cb2a_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.0.0
      - alabaster==0.7.13
      - anndata==0.8.0
      - anyio==3.7.1
      - anykeystore==0.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - build==1.0.3
      - cachetools==5.3.2
      - charset-normalizer==3.2.0
      - comm==0.1.4
      - cryptacular==1.6.2
      - cupy-cuda112==10.6.0
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docutils==0.18.1
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - fastjsonschema==2.18.0
      - fastrlock==0.8.2
      - fonttools==4.38.0
      - glob2==0.7
      - google-auth==2.26.1
      - google-auth-oauthlib==0.4.6
      - greenlet==3.0.3
      - grpcio==1.60.0
      - h5py==3.8.0
      - hupper==1.12
      - imageio==2.31.2
      - imagesize==1.4.1
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - jaraco-classes==3.2.3
      - jedi==0.19.0
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.9
      - keyring==24.1.1
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.1
      - more-itertools==9.1.0
      - natsort==8.4.0
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.7
      - networkx==2.6.3
      - notebook==6.5.5
      - notebook-shim==0.2.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - openslide-python==1.2.0
      - opt-einsum==3.3.0
      - packaging==21.0
      - pandas==1.3.5
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pastedeploy==3.1.0
      - pbkdf2==1.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==23.3.2
      - pkginfo==1.9.6
      - pkgutil-resolve-name==1.3.10
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python3-openid==3.2.0
      - pytz==2023.3.post1
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==24.0.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - readme-renderer==37.3
      - repoze-sendmail==4.4.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.0
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - send2trash==1.8.2
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - soupsieve==2.4.1
      - sphinx==5.3.0
      - sphinx-argparse==0.4.0
      - sphinx-autodoc-typehints==1.23.0
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-programoutput==0.17
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlalchemy==2.0.25
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchvision==0.14.0
      - tornado==6.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - transaction==4.0
      - translationstring==1.4
      - twine==4.0.2
      - typing-extensions==4.7.1
      - urllib3==2.0.4
      - velruse==1.1.1
      - venusian==3.1.0
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - webob==1.8.7
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.9
      - wtforms==3.0.1
      - wtforms-recaptcha==0.3.2
      - zipp==3.15.0
      - zope-deprecation==5.0
      - zope-interface==6.1
      - zope-sqlalchemy==3.1
prefix: /home/zaraki/miniconda3/envs/scc
